version: '2'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    ports:
      - 5000:5000
    build:
      context: backend/
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
    depends_on:
      - mongo
  frontend:
    ports:
      - 4000:3000
    build:
      context: frontend/
    stdin_open: true
    depends_on:
      - backend
